version: "3.7"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports: 
      - 5431:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=poc-kafka
    volumes:
      - poc-kafka:/postgresql/data

volumes:
  poc-kafka:
